### ISSUE TITLE
Add glowing effects

### ISSUE THREAD

**Issue by Marimboi3** [Marimboi3/XCITE-Enigma-Machine-VR#15]
- In the cipher machine, add blinking glowing effect to indicate what the user should touch to make the knob rotate
- In the enigma machine, add a blink for the encryption/decryption light when user presses a key

**Comment by Zelocity** [comment]
- machine currently blinks on and off for all letters. Need to make only the pressed letter glow.

**Comment by Zorten** [comment]
Glowing functionality needed to implement:

1. Make the glow gradual, as opposed to ON/OFF
2. Start with outer text glowing, and once no longer glowing make inner text glow, and then keep switching
3. Once a letter is clicked, only that letter should glow for the respective knob, while the other one should keep glowing up/down to indicate selection needed on other knob. 
4. Once this is done, only glow selected letters. 
6. When new letter is selected, repeat functionality from step 3.
